name: Build links-extractor docker image

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      -
        name: set TIMESTAMP environment variable
        run: echo "TIMESTAMP=$(date +'%Y%m%d.%H:%M:%S') >> $GITHUB_ENV"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     file: ./docker/links-extractor.yml
      #     push: true
      #     tags: evansalda/links-extractor:github-actions-${{ env.TIMESTAMP }}, latest

      -
        name: Build and push
        run: |
          docker build . -f .docker/links-extractor.yml -t evansalda/links-extractor:github-actions-${{ env.TIMESTAMP }} -t evansalda/links-extractor:latest
          docker push evansalda/links-extractor:github-actions-${{ env.TIMESTAMP }}
          docker push evansalda/links-extractor:latest