name: Build and deploy links-extractor app

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      -
        name: set TIMESTAMP environment variable
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%Hh%Mm%Ss')" >> $GITHUB_ENV

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/links-extractor.yml
          push: true
          tags: evansalda/links-extractor:github-actions-${{ env.TIMESTAMP }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      -
        name: Code checkout
        uses: actions/checkout@v4

      -
        name: Set up gcloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      -
        name: Set up GKE creds
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: anonymous-case-study
          location: europe-west1

      -
        name: Application deployment
        run: |
          kubectl kustomize kube/  
          kubeclt apply -f kube/deployment.yml