name: Build and deploy links-extractor app

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-envs.outputs.IMAGE_TAG }}
    steps:
      -
        name: set IMAGE_TAG environment variable
        id: set-envs
        run: |
          image_tag=github-actions-$(date +'%Y%m%d-%Hh%Mm%Ss')
          echo "IMAGE_TAG=$image_tag" >> $GITHUB_ENV
          echo "IMAGE_TAG=$image_tag" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push the docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: evansalda/links-extractor:${{ env.IMAGE_TAG }}

      -
        name: Run vulnerability scanner on docker image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: evansalda/links-extractor:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          severity: UNKNOWN,LOW,MEDIUM,CRITICAL,HIGH

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Code checkout
        uses: actions/checkout@v4
      -
        name: Set up gcloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      -
        name: Set up GKE creds
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: anonymous-case-study
          location: europe-west1
      -
        name: Application deployment
        env:
          IMAGE_TAG: ${{needs.build.outputs.image_tag}}
        run: |
          envsubst < kube/deployment.yml | kubectl apply -f -